harshvardhansb/TourGuide

- Contribute.md
Reverts harshvardhansb/TourGuide#44
> Revert "Update Contribute.md"

- index.html
- style.css
Added a shortcut which directly takes user to Top of the page from bottom of the page without scrolling back to the Top.
> Added a shortcut

- index.html
Added icon which was not visible due to some text errors.
> Added icon visibility

- index.html
- index.js
- style.css
> Added theme changer

- index.js
- style.css
> Added icon in square

- index.html
- style.css
Hey @harshvardhansb Plz look on this Pr. I added pagination and footer for better look of your website.Plz Merge it in ur repo
> Added Pagination for all cards and made footer

- index.html
-Previously, the image card was not visible because of a typo 
-Fixed the typo 
See Issue: #105
> Renamed the Image index

- index.html
- slider.js
- sliderStyle.css
- style.css
@harshvardhansb Please Review this .
This aligns with issue #113.
> COOL Image slider Added to Website

- style.css
> added hover transition effect on city card.

- index.html
- I am adding one of the best National Parks in Maharashtra 
- It's the international tourist attraction in Vidarbha Maharashtra in district Chandrapur
> Add Tadoba National Park in Maharashtra

- README.md
> improved the Readme

- index.html
- I am adding shivneri fort which is one of the best tourist places in maharashtra
> Add shivneri fort tourist place as a card

- style.css
Reverts harshvardhansb/TourGuide#150
> Revert "Added custom scrollbar"

- index.html
- style.css
issue #131 
Adding Social Media icons to the footer and improving footer
> Adding Social Media icons to the footer and improving footer

- index.html
closes #163 
closes #161 
fixed pagination , ensured 3 cards per row , fixed nalanda image url
> fixed pagination , ensured 3 cards per row , fixed nalanda image url

- index.html
- style.css
resolved issue #165 
Screenshots:
> Modified the social icons in the footer

- style.css
> Fixed the visibility of pagination text

- index.html
- style.css
Title - Manali
Description -  Issue no: [#3]
> Added Location and new card [#3]

- index.html
Signed-off-by: Prakash <gatiyalap@gmail.com>
Issue No: https://github.com/harshvardhansb/TourGuide/issues/172
Hi @harshvardhansb Please review it and merge it.
> Fix email link at footer

- index.html
- style.css
added animation in the header on loading using keyframes in the CSS
> added animation in navbar

- README.md
@harshvardhansb Please review. I have made some changes.
> [Docs update]: made changes in readme.md

- index.html
> feat: add missing meta description

- README.md
Added Location anchor in Element template in the ReadMe.
Solved Issue #186
> [Feat] Added Location anchor in Element template

- style.css
> #190 fixed the responsiveness issue

- index.html
> feat- Adding missing locations

- index.html
Solved Issue #175 , #177 , #197
> [Fixed] Solved Issue #175 , #177 , #197

- Contribute.md
- index.html
- style.css
Last night i added expandable contact form button which had conflicts, doing it again without conflicts.
Added a "Contact Us" Button at the footer.
Once the button is clicked, it expands into a collapsable in-page form.
The contact us form is basically the requests of the users who want reviews of new places which isnt already included in the page.
The Button when its collapsed
The Button when its expanded
> revised the contact form button without conflicts

- Contribute.md
- index.html
>  Kalipaltan

- index.html
> Worlds of Wonder

- style.css
Hey @harshvardhansb i have corrected the alignment of the Toggle Button. Please help me merge it as soon as possible.
Thanks !!
> Fixed the alignment of Toggle button

- index.html
@harshvardhansb 
Fixed text allignment issue.
Created a seperate row to fix the issue.
This PR closes #207
> fix footer text alignment issue

- index.html
- index.js
Issue No #209
Solution{
Added mailto Function for Submit Button in Contact Form;
}
> Fix : Added mailto Function for Submit Button in Contact Form

- index.html
- style.css
fixes: #215 
colour  correction in dark mode
> changed contact us form in dark colour correction

- style.css
Centering pagination for a better user experience.
> Centering pagination

- index.html
- index.js
- style.css
Fix the contact us form, refactor mailto logic and fix unnecessary bottom padding for "contact us form" button.
> Fix. Issue #209 contact us form

- index.html
- style.css
Refactor scroll to top for mobile devices and change theme button position on header.
> Fix. Issue #226 scroll to top and theme changer button

- style.css
Update the overflow in x direction, by adding the overflow-x hidden to the body in style.css file
> Update the overflow in x direction

- sliderStyle.css
- style.css
This change resolves the issue #237 by adding responsiveness to the website. The SS of the resultant UI are attached.
> Adding responsiveness to the website

- index.html
- style.css
fixes #244 
This pull request aims to enhance the user experience by adding a smooth scroll functionality when navigating to the top of the page. Additionally, a fade effect is introduced for the "Back to Top" button using jQuery. This improvement will provide a more polished and visually appealing interaction for our website visitors.
**Changes Made**:
Smooth Scroll: Implemented smooth scrolling behavior using jQuery. When the "Back to Top" button is clicked, the page smoothly scrolls to the top.
Button Fade Effect: Added a fade effect to the "Back to Top" button. The button becomes visible as the user scrolls down and fades out when the user is at the top of the page.
**Results**
https://github.com/harshvardhansb/TourGuide/assets/78639134/e179b838-67ab-45bd-96a2-4a8deeeaae8e
> Add Smooth Scroll and Button Fade Effect

- index.html
- style.css
> Solved An error Showing over Navigation Bar

- .vscode/settings.json
- index.html
- index.js
- style.css
This  PR removed the hamburger menu and changed the dark mode button design. The design was taken from [link](https://uiverse.io/rishichawda/fluffy-robin-48).
Fixes:#249
The previous code was commented out and not deleted, as it may be used in the future.
> feat: Removed hamburger menu and changed dark mode button design 

- style.css
now mobile users will not see the icon as it is disabled.
> fix:changed the bottom to top arrow icon for mobile users

- index.html
- style.css
I have successfully added the feature of search bar in the header of the page 
which is compatibe in monile and pc view 
mobile view:
pc view:
> fix:  #262   feature of search bar, compatible in mobile and phone view

- index.html
Corrected up the Issue #276 and also added up the 2 card .
and also corrected up the code 
pls label the issue #276 with ` hacktoberfest` and PR with `hacktoberfest-accepted`.
> Fix:issue_276_added_cards_on_page16

- index.html
The search bar does not redirect you to the desired page. Hence adding a feature to redirect to the wikipedia page for that place would enhance the user experience.
https://github.com/harshvardhansb/TourGuide/assets/120674432/d8b5f550-511d-4183-9bad-f7b87bc4efe8
> Redirection to the wikipedia page once a place is searched .

- Contribute.md
> updated Contribute.md file

- index.html
Copyright year was static so changed it by adding Js so that it can be autoupdated,Under issue-  Enhance UI using HTML CSS JavaScript #222
Issue-#222
> Copyright year was static so changed it by adding Js so that it can be autoupdated,Under issue-  Enhance UI using HTML CSS JavaScript #222

- Contribute.md
- index.html
title: Mahakaleshwar Jyotirlinga
description: Issue no: #4
> Please add mr contribution

- Docker.txt
- Dockerfile
I Have Added docker and docker.txt for the instruction manual of the docker in your repository according to issue #298
> Added DockerFile and added docker.txt for instructions

- index.html
PR for issue #296
Made the "See location" links consistent and go to the correct URL
> Rectified the See Location links and made them consistent

- index.html
Update description of backwaters and beaches.
> add new section.

- .vscode/settings.json
- index.html
- style.css
Made some changes in the footer and the website was aligned weirdly so I've improved that too.
Fixes issue number #312
> footer improvements
